name: brompton_parser
description: Attempts to parse brompton api docs into an openapi doc because brompton hates standards
version: 1.0.0

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  json2yaml: ^3.0.0
  open_api_forked: ^3.0.0+6

dev_dependencies:
  dart_code_metrics: ^5.0.1
  lints: ^2.0.0
  test: ^1.16.0
